import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Plus_Jakarta_Sans, Libre_Franklin  } from "@next/font/google";
import "./globals.css";
import "./globals.scss"


const libreFranklin = Libre_Franklin({
  weight: ["200", "400", "700"], // You can specify multiple weights
  subsets: ["latin"], // Specify the subsets you need
  variable: "--font-libreFranklin", // CSS variable name
});
// use the class name - font-[family-name:var(--font-libreFranklin)]

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["200", "400", "700"], // You can specify multiple weights
  subsets: ["latin"], // Specify the subsets you need
  variable: "--plusjakart", // CSS variable name
});
// use the class name - font-[family-name:var(--plusjakart)]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${plusJakartaSans.variable} ${plusJakartaSans.className} ${libreFranklin.variable} ${libreFranklin.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
