import type { Metadata } from "next";
import localFont from "next/font/local";
import { Plus_Jakarta_Sans   } from "@next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


// const plusJakartaSans = Plus_Jakarta_Sans({
//   weight: ["200", "400", "700"], // You can specify multiple weights
//   subsets: ["latin"], // Specify the subsets you need
//   variable: "--plusjakart", // CSS variable name
// });
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["200", "400", "700"], // You can specify multiple weights
  subsets: ["latin"], // Specify the subsets you need
  variable: "--plusjakart", // CSS variable name
});
// use the class name - font-[family-name:var(--plusjakarta)]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${plusJakartaSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
